---
title: Distance in Reward-Based crowdfunding 
author: Ludovic Vigneron
date: '2022-09-17'
slug: []
categories:
  - recherche
  - Finance
tags:
  - Publication
  - Finance
  - Crowdfunding
---

**La version finale du papier que j’ai écrit sur l’effet de la distance entre porteur de projet/contributeurs sur la réussite des campagnes de crowdfunding et que a été accepté dans la revue Finance est disponible sur CAIRN. Je vous met le lien correspondant à la suite ainsi que le résumé en anglais. Je suis très content du résultat. Le travail préparatoire m’a donné l’occasion de travailler la réalisation de cartes ce qui est peu courant en finance. Il n’en reste qu’une dans la version finale et elle est en nuance de gris (la revue ne prend pas les couleurs). Néanmoins, l’ensemble m’a permis de pas mal progresser dans le domaine. J’espère pouvoir renouveler l’expérience et intégrer de nouvelles cartes dans de prochains travaux.**

[Distance in Reward-Based crowdfunding](https://www-cairn-info.fr/revue-finance-2022-0-page-I10.htm)

This paper questions the impact of the distance between backers and entrepreneurs has on the success of reward-based crowdfunding campaigns. Using a unique dataset provided by the Ulule platform, we show that those attracting more distant backers succeed more frequently and more intensively. Successful campaigns attracting the most distant backers (the more numerous ones) are also those for which the supports average amount is the smallest and those with more numerous backers. Successful campaigns that attract less distant backers collect supports with a higher average amount from fewer ones. This pattern is in line with the double hypothesis that “broad scope” campaigns rely more on entrepreneurs’ weak ties to succeed and that “local” ones rely more on entrepreneurs’ strong ties. We also find evidences that successful campaigns attract more distant backers from the beginning than failed ones. This findings contradict the classical view of campaigns reaching progressively a broader public (farer backers) with time.

KEYWORDS: reward-based crowdfunding, campaign’s success, entrepreneur’s social capital, geographic distance, weak ties versus strong ties

DOI: https://doi-org.ressources-electroniques.univ-lille.fr/10.3917/fina.pr.010 

Pour ceux qui voudraient voir la carte en couleur, je glisse le lien avec la version de travail disponible sur le site du SSRN : https://papers.ssrn.com/sol3/papers.cfm?abstract_id=3698562
