---
title: Who to attract at the begining?
author: Ludovic Vigneron
date: '2021-09-23'
slug: []
categories:
  - recherche
tags:
  - Crowdfunding
  - SNA
  - Publication
---

Après un long processus de soumission/révisions (débuté en 2017), qui a grandement contribué à améliorer le papier, nous sommes parvenu ma coautrice, Karima Bouaiss, et moi à publier notre étude sur l'impact de la forme que prend l'articulation des goûts des premiers contributeurs à une campagne de crowdfunding avec ceux des autres utilisateurs de la plateforme sur sa réussite. Nous y proposons notamment une modélisation de l'articulation complexe des goûts de chacun au travers d'un réseau construit sur la base des préférences révélées par les choix de supports passés. Ce travail, dont je met le résumé (en anglais) et le lien à la suite dans ce post, a été pour nous l'occasion d'apprendre énormément. Il nous a notamment fait touché du doigt ce que les spécialistes du big data affronte tout les jours la malédiction de la dimensionalité. J'espère que sa lecture vous en sera bénéfique.

**[Reward Crowdfunding: Who to Attract at the Beginning of the Campaign? An Analysis in Terms of Revealed Networks of Preferences](https://management-aims.com/index.php/mgmt/article/view/4530)**

*Bouaiss, K., & Vigneron, L. (2021).M@n@gement, 24(3), 19–40.*

This research study combines the theoretical teachings of revealed preferences, signal theory and weak tie theory to better understand the dynamics at work at the beginning of a campaign and to explain its success. By identifying the revealed preferences of early backers through their common past contributions, we characterize as strong or weak the nature of the complex preference ties between them. We build networks of the contributions made by the individuals identified as early backers to 9,425 campaigns run on the Ulule platform between July 2010 and September 2014. The results of this study underline the importance of the presence of strong preference ties between early backers and other platform users for the success of campaigns. They also corroborate the theory of the strength of weak ties. Later in the campaign, the intervention of backers with less specific preferences, in the position of intermediaries, positively influences the future outcome by accelerating the fundraising speed at the beginning of the campaign. 

Keywords: Social network, Social capital, Reward crowdfunding, Early backers, Revealed preferences, Graph theory

DOI: [https://doi.org/10.37725/mgmt.v24.4530](https://doi.org/10.37725/mgmt.v24.4530)



