<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="google-site-verification" content="gvTIRAZF7KZCKm-syPBJcDj0JiQpJqR6f6uq6PCfZYs" />

        <meta property="og:title" content="Police academie" />
<meta property="og:description" content="La personnalisation d’un graphe passe aussi par celle des textes qui l’accompagnent. Que ce soit son titre, sa légende ou tout autres annotations, une mise en forme s’impose. Nous l’avons vu celle-ci est possible dans GGPLOT2 au travers des éléments du thème retenu. Il s’agit d’indiquer, au sein de l’ajout de mise en forme introduit par la fonction theme(), l’objet sur lequel vous voulez appliquer votre choix et de l’introduire par la fonction element_text()." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/post/2021-09-02-police-academie/" /><meta property="article:section" content="post" />
<meta property="article:published_time" content="2021-09-02T00:00:00+00:00" />
<meta property="article:modified_time" content="2021-09-02T00:00:00+00:00" />


        <meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Police academie"/>
<meta name="twitter:description" content="La personnalisation d’un graphe passe aussi par celle des textes qui l’accompagnent. Que ce soit son titre, sa légende ou tout autres annotations, une mise en forme s’impose. Nous l’avons vu celle-ci est possible dans GGPLOT2 au travers des éléments du thème retenu. Il s’agit d’indiquer, au sein de l’ajout de mise en forme introduit par la fonction theme(), l’objet sur lequel vous voulez appliquer votre choix et de l’introduire par la fonction element_text()."/>
<meta name="twitter:site" content="@VigneronLudovic"/>

        
        <title>
  Police academie | My Econ Tricks
</title>

        <link rel="icon" type="image/png" href='/images/favicon-16x16.png' sizes="16x16">
        <link rel="icon" type="image/png" href='/images/favicon-32x32.png' sizes="32x32">  

        <link href="https://fonts.googleapis.com/css?family=Oswald:400" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">      
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
        
        
        
        

        <link rel="stylesheet" href="/css/bundle.min.3c1ab42be3f0635203d9e8bbe9cd3da817ca1d442ea586b8d8de6a4853e0d743.css" integrity="sha256-PBq0K&#43;PwY1ID2ei76c09qBfKHUQupYa42N5qSFPg10M="  />

        
    <link rel="me" type="text/html" href="https://twitter.com/VigneronLudovic"/> 
<link rel="me" type="text/html" href="https://www.linkedin.com/in/ludovic-vigneron-1ba27749/"/> 
<link rel="icon" type="image/png" href="/images/favicon-16x16.png" sizes="16x16">
<link rel="icon" type="image/png" href="/images/favicon-32x32.png" sizes="32x32">

<link rel="alternate" type="application/rss+xml" href='/index.xml' />

<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
<meta name="author" content="My Econ Tricks" />
<meta name="copyright" content="© Ludovic Vigneroin 2021–2022. All rights reserved." />
<meta name="google-site-verification" content="gvTIRAZF7KZCKm-syPBJcDj0JiQpJqR6f6uq6PCfZYs" />


<meta name="description" content="La personnalisation d’un graphe passe aussi par celle des textes qui l’accompagnent. Que ce soit son titre, sa légende ou tout autres annotations, une mise en forme s’impose. Nous l’avons vu celle-ci est possible dans GGPLOT2 au travers des éléments du thème retenu. Il s’agit d’indiquer, au sein de l’ajout de mise en forme introduit par la fonction theme(), l’objet sur lequel vous voulez appliquer votre choix et de l’introduire par la fonction element_text().">


    
        
    </head>
    <body>
        <nav class="navbar fixed-top navbar-expand-md navbar-dark bg-dark py-1 top-nav">
            <div class="container">
                    <a class="navbar-brand pr-2" href="/">MY ECON TRICKS</a>
                <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="navbar-collapse collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
    <a class="nav-link active" href="/about/">A propos</a>
</li>
<li class="nav-item">
    <a class="nav-link active" href="/categories/recherche/">Recherche</a>
</li>
<li class="nav-item">
    <a class="nav-link active" href="/categories/datavisualisation/">Datavisualisation</a>
</li>
<li class="nav-item">
    <a class="nav-link active" href="/categories/r/">R</a>
</li>

                    </ul>
                    <div class="social-icons d-none d-lg-block">
                        <a class="py-2 px-2" href="https://twitter.com/VigneronLudovic"><i class="fab fa-twitter"></i></a>
<a class="py-2 px-2" href="https://www.linkedin.com/in/ludovic-vigneron-1ba27749/"><i class="fab fa-linkedin"></i></a>
<a class="py-2 px-2" href='/index.xml'><i class="fas fa-rss"></i></a>

                    </div>
                </div>
            </div>
        </nav>

        
<header class="feature-image d-print-none">
</header>

        
        <div class="main">
            
<div class="container mt-4 post">
    <h1>Police academie</h1>
    <div class="mb-3">
    <small>
        <strong>By Ludovic Vigneron</strong>
        | <i class="far fa-calendar-alt"></i>&nbsp;Sep 2, 2021&nbsp;
        | <i class="fa fa-tags" title="Tags" aria-hidden="true"></i> <a href='/tags/ggplot2/'>ggplot2</a>, <a href='/tags/dataviz/'>dataviz</a>
    </small>
</div>

    <div class="share-icons d-flex justify-content-center d-print-none">
        <a href="https://twitter.com/intent/tweet?url=%2fpost%2f2021-09-02-police-academie%2f&text=Police%20academie&tw_p=tweetbutton" class="p-2" title="Share on Twitter" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Tweet</small></div>
</a>

<a href="https://www.facebook.com/sharer.php?u=%2fpost%2f2021-09-02-police-academie%2f&t=Police%20academie" class="p-2" title="Share on Facebook" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-facebook fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Share</small></div>
</a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=%2fpost%2f2021-09-02-police-academie%2f&title=Police%20academie&source=mattbutton.com" class="p-2" title="Share on LinkedIn" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Share</small></div>
</a>

<a href="javascript:window.print()" title="Print this article" class="p-2" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fa fa-print fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Print</small></div>
</a>
    </div>

    <div class="mt-4 mb-4 main-content">
        
<script src="/post/2021-09-02-police-academie/index_files/header-attrs/header-attrs.js"></script>
<script src="/post/2021-09-02-police-academie/index_files/kePrint/kePrint.js"></script>
<link href="/post/2021-09-02-police-academie/index_files/lightable/lightable.css" rel="stylesheet" />


<p>La personnalisation d’un graphe passe aussi par celle des textes qui l’accompagnent. Que ce soit son titre, sa légende ou tout autres annotations, une mise en forme s’impose. Nous l’avons vu celle-ci est possible dans GGPLOT2 au travers des éléments du thème retenu. Il s’agit d’indiquer, au sein de l’ajout de mise en forme introduit par la fonction <strong>theme()</strong>, l’objet sur lequel vous voulez appliquer votre choix et de l’introduire par la fonction <strong>element_text()</strong>. Celle-ci permet entre autre de changer la police, l’encrage, le centrage, l’orientation, la couleur… Dans ce nouveau post, nous nous focaliserons sur ces modifications. Bien souvent, les graphes produits sont amenés à s’intégrer dans des rapports (ou d’autres supports). Il peut être intéressant de s’assurer d’une continuité de forme en faisant en sorte que la police utilisée dans les graphes soit la même que celle utilisée dans le reste du document.</p>
<p>Pour illustrer les méthodes mises en oeuvre, reprenons (une nouvelle fois) notre série temporelle des moyennes annuelles de températures sur le centre de l’Angleterre de 1772 à nos jours. Pour cela, importons à nouveau les données, procédons aux transformations habituelles et stockons l’ensemble dans la une data frame nommée dat.</p>
<pre class="r"><code>library(tidyverse)
dat&lt;-read.table(&quot;https://hadleyserver.metoffice.gov.uk/hadcet/cetdl1772on.dat&quot;)
colnames(dat)&lt;-c(&#39;year&#39;,&#39;day&#39;,paste0(&#39;month_&#39;,1:12))
dat&lt;-dat%&gt;%pivot_longer(cols=starts_with(&#39;month_&#39;),names_to=&quot;month&quot;,
                         names_prefix=&#39;month_&#39;,values_to=&#39;d_t&#39;)%&gt;%
            mutate(date=as.Date(paste0(day,&#39;/&#39;,month,&#39;/&#39;,year),
                                format=&#39;%d/%m/%Y&#39;,origin=&#39;1/1/1990&#39;))%&gt;%
            select(date,d_t)%&gt;%
            arrange(date)%&gt;%
            mutate(d_t=ifelse(d_t==-999,NA,d_t),
                   degre_C=d_t/10)%&gt;%
            filter(is.na(d_t)==FALSE)%&gt;%
            select(-d_t)
dat&lt;-dat%&gt;%mutate(annee=lubridate::year(date))%&gt;%
            group_by(annee)%&gt;%
            summarise(deg_C=round(mean(degre_C),digits=2))</code></pre>
<p>Ceci fait, établissons un graphe de base à partir duquel nous travaillerons. Prenons le même nuage de points que dans les posts précédant habillé avec le thème minimal et la légende placée en dessous. Appelons-le G1.</p>
<pre class="r"><code>G1&lt;-ggplot(dat,aes(x=annee,y=deg_C))+geom_point()+geom_smooth(se=FALSE,aes(colour=&quot;Courbe d&#39;ajustement (loess)&quot;))+
           geom_hline(aes(yintercept=mean(deg_C),colour=&quot;Moyenne&quot;))+
           labs(title=&quot;Températures moyennes au centre de l&#39;Angleterre (1772-2021)&quot;,
               subtitle=&quot;Nuage de points&quot;,
               caption=&quot;Données: centre Hadley [Parker, Legg et Folland (1992)]&quot;,
               x=&#39;Années&#39;,y=&#39;°C&#39;)+
           scale_colour_manual(name=&quot;Légende&quot;, values=c(&quot;blue&quot;, &quot;red&quot;))+theme_minimal()+
           theme(legend.position = &quot;bottom&quot;)
G1</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Maintenant que nous avons une base de travail, voyons comment avancer sur la personnalisation.</p>
<div id="identifier-les-polices-disponibles-par-défaut" class="section level2">
<h2>Identifier les polices disponibles par défaut</h2>
<p>Commençons par voir quelles polices sont disponibles sans qu’il ne soit nécessaire de faire quoique ce soit. Profitons-en pour relever les noms qu’il faut utiliser afin les mobiliser via l’option <em>family</em>. La fonction <strong>windowsFonts()</strong>, nous en renvoie le liste.</p>
<pre class="r"><code>windowsFonts()</code></pre>
<pre><code>## $serif
## [1] &quot;TT Times New Roman&quot;
## 
## $sans
## [1] &quot;TT Arial&quot;
## 
## $mono
## [1] &quot;TT Courier New&quot;</code></pre>
<p>Elle présente trois éléments. Le premier, que l’on connait déjà, est nommé serif. Il permet d’utiliser la police “<em>Times New Roman</em>”. Celle-ci est assez élégante. On la retrouve souvent dans les documents voulant un rendu proche de celui d’un livre. Le second est nommé sans. Il permet d’utiliser la police “<em>Arial</em>” qui est plus angulaire, plus proche de ce que l’on lit sur un écran. Le troisième est nommé mono. Il permet d’utiliser la police “<em>Courier New</em>”. Comme toute les polices courriers, elle a la particularité de présenter des caractères qui ont tous la même taille (comme sur les anciennes machines à écrire).</p>
<p>Utilisons ces différentes polices pour personnaliser G1. Passons le titre à la police “<em>Time New Roman</em>” avec encrage gras (option <em>face</em>), le sous-titre en “<em>Courier New</em>” avec encrage italique et le contenu de la légende en police “<em>Arial</em>” sans modifier l’encrage.</p>
<pre class="r"><code>G1+theme(plot.title = element_text(family = &#39;serif&#39;,face=&#39;bold&#39;),
         plot.subtitle = element_text(family = &#39;mono&#39;,face=&#39;italic&#39;),
         legend.text = element_text(family = &#39;sans&#39;))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<p>On remarque qu’il n’y a pas de changement apparent sur la légende. Celle-ci comme tout les éléments textuels du graphe à l’exception de ceux que nous avons modifié sont établis avec la police “<em>Arial</em>”.</p>
</div>
<div id="obtenir-de-nouvelles-polices" class="section level2">
<h2>Obtenir de nouvelles polices</h2>
<p>Trois polices disponibles, cela parait assez limité. Voyons comment étendre ce nombre. Plusieurs packages le permettent (extrafont,…). Concentrons-nous sur le plus simple d’utilisation: showtext. Il permet non seulement d’intégrer les autres polices d’écriture stockées dans votre système d’exploitation, mais aussi celles mise à disposition par google. Installons-le (<strong>install.packages()</strong>), appelons-le (<strong>library()</strong>) et utilisons la fonction <strong>font_files()</strong> pour obtenir la liste des polices installées. Afin de ne pas alourdir le document, nous nous limiterons ici aux 10 premières lignes (avec une légère mise en page).</p>
<p>’</p>
<center>
<p><strong>10 premières lignes de la liste des fichiers font du système</strong></p>
</center>
<p>’</p>
<table class="table table-striped" style="margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:left;">
path
</th>
<th style="text-align:left;">
file
</th>
<th style="text-align:left;">
family
</th>
<th style="text-align:left;">
face
</th>
<th style="text-align:left;">
version
</th>
<th style="text-align:left;">
ps_name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
AGENCYB.TTF
</td>
<td style="text-align:left;">
Agency FB
</td>
<td style="text-align:left;">
Bold
</td>
<td style="text-align:left;">
Version 1.01
</td>
<td style="text-align:left;">
AgencyFB-Bold
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
AGENCYR.TTF
</td>
<td style="text-align:left;">
Agency FB
</td>
<td style="text-align:left;">
Regular
</td>
<td style="text-align:left;">
Version 1.01
</td>
<td style="text-align:left;">
AgencyFB-Reg
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
Alef-Bold.ttf
</td>
<td style="text-align:left;">
Alef
</td>
<td style="text-align:left;">
Bold
</td>
<td style="text-align:left;">
Version 1.001;PS 001.001;hotconv 1.0.56;makeotf.lib2.0.21325
</td>
<td style="text-align:left;">
Alef-Bold
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
Alef-Regular.ttf
</td>
<td style="text-align:left;">
Alef
</td>
<td style="text-align:left;">
Regular
</td>
<td style="text-align:left;">
Version 1.001;PS 001.001;hotconv 1.0.56;makeotf.lib2.0.21325
</td>
<td style="text-align:left;">
Alef-Regular
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
ALGER.TTF
</td>
<td style="text-align:left;">
Algerian
</td>
<td style="text-align:left;">
Regular
</td>
<td style="text-align:left;">
Version 1.57
</td>
<td style="text-align:left;">
Algerian
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
Amiri-Bold.ttf
</td>
<td style="text-align:left;">
Amiri
</td>
<td style="text-align:left;">
Bold
</td>
<td style="text-align:left;">
Version 000.111
</td>
<td style="text-align:left;">
Amiri-Bold
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
Amiri-BoldSlanted.ttf
</td>
<td style="text-align:left;">
Amiri
</td>
<td style="text-align:left;">
Bold Slanted
</td>
<td style="text-align:left;">
Version 000.111
</td>
<td style="text-align:left;">
Amiri-BoldSlanted
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
Amiri-Regular.ttf
</td>
<td style="text-align:left;">
Amiri
</td>
<td style="text-align:left;">
Regular
</td>
<td style="text-align:left;">
Version 000.111
</td>
<td style="text-align:left;">
Amiri-Regular
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
Amiri-Slanted.ttf
</td>
<td style="text-align:left;">
Amiri
</td>
<td style="text-align:left;">
Slanted
</td>
<td style="text-align:left;">
Version 000.111
</td>
<td style="text-align:left;">
Amiri-Slanted
</td>
</tr>
<tr>
<td style="text-align:left;">
C:/Windows/Fonts
</td>
<td style="text-align:left;">
AmiriQuran.ttf
</td>
<td style="text-align:left;">
Amiri Quran
</td>
<td style="text-align:left;">
Regular
</td>
<td style="text-align:left;">
Version 000.111
</td>
<td style="text-align:left;">
AmiriQuran-Regular
</td>
</tr>
</tbody>
</table>
<p>Pour les utilisateurs de Windows, il peut être plus simple de consulter la sections “<a href="https://docs.microsoft.com/en-us/typography/fonts/windows_10_font_list">typography</a>” du site de Microsoft. On y retrouve un tableau présentant notamment le nom de la police, sa familly et le nom du fichier le stockant dans le système. Si vous cliquez sur le lien idoine, vous pouvez visualiser un aperçu de la police qui vous intéresse.</p>
<p>Pour utiliser l’une de ces polices dans vos graphes, il suffit de l’appeler avec la fonction <strong>font_add()</strong> en indiquant sa familly et le nom du fichier (.ttf) qui la stock. Reste alors à annoncer que vous mobilisez showtext grâce à la fonction <strong>showtext_auto()</strong> pour pouvoir l’utiliser dans <strong>element_text()</strong>. Voyons un exemple rapide avec la police “<em>Comic Sans MS</em>”. Celle-ci a la particularité de présenter de arrêtes arrondies.</p>
<pre class="r"><code>font_add(&quot;Comic Sans MS&quot;, &quot;comic.ttf&quot;)
showtext_auto()
G1+theme(text=element_text(family = &quot;Comic Sans MS&quot;,size=18))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Le changement n’est pas spectaculaire. Essayons avec une police plus originale. Prenons celle nommée Harrington qui est stockée dans le fichier Harngton.ttf.</p>
<pre class="r"><code>font_add(&quot;Harrington&quot;, &quot;Harngton.ttf&quot;)
showtext_auto()
G1+theme(text=element_text(family = &quot;Harrington&quot;,size=18))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>Si l’ensemble des polices classiques ne suffit pas pour combler vos désirs de personnalisation, vous pouvez également de la même manière importer celles proposées par Google. Il y en a 1092… Pour en avoir un aperçu, il suffit de visiter le site <a href="https://fonts.google.com">fonts.google.com</a>. La fonction permettant d’appeler la police est alors <strong>font_add_google()</strong>. Testons-la avec la police “<em>Montserrat</em>”, que je trouve très élégante. Les arguments sont cette fois le nom de la police et le nom que vous utiliserez pour sa family.</p>
<pre class="r"><code>font_add_google(&quot;Montserrat&quot;, &quot;Montserrat&quot;)
G1+theme(text = element_text(family = &quot;Montserrat&quot;,size=18))</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>Testons-en deux autres pour le plaisir: une, que nous appliquerons au titre, et une, que nous appliquerons au caption. Le reste restera en “<em>Arial</em>”. Prenons celle nommée “<em>Rock Salt</em>” pour le titre et celle nommée “<em>Architects Daughter</em>” pour le caption.</p>
<pre class="r"><code>font_add_google(&quot;Rock Salt&quot;,&quot;rock&quot;)
font_add_google(&quot;Monoton&quot;,&quot;monoton&quot;)
showtext_auto()
G1+theme(plot.title = element_text(family = &quot;rock&quot;,size=12),
         plot.caption = element_text(family = &quot;monoton&quot;,size=10))</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="aller-plus-loin-dans-la-personnalisation" class="section level2">
<h2>Aller plus loin dans la personnalisation</h2>
<p>Comme nous l’avons vue dans le premier <a href="https://myecontricks.netlify.app/post/2021-08-23-premiers-pas-sur-ggplot2/">post de cette série</a>, il possible d’aller au-delà du changement de police (ou d’autres éléments de mise en forme) qui s’appliquera de manière uniforme sur une partie désignée du thème (titre, légende, axe…). Grâce au package ggtext, on peut avoir une approche plus fine en intégrant des instructions en markdown et en html à l’intérieur même des textes traités par ggplot pour être intégré au graphe. Pour cela, il ajoute à la liste des fonctions de personnalisation de thème <strong>element_markdown()</strong>.</p>
<p>Utilisons-la afin de retravailler notre titre. Commençons simplement par mettre l’ensemble en gras à l’exception de la parenthèse reprenant les dates que l’on mettra en italique. Pour le gras, il suffit d’entourer le partie du texte visée de paquets de deux astérisques (**). Pour l’italique, il suffit de l’entourer de deux astérisques(<em>*</em>). Il n’y a rien de spectaculaire ici. Voyons si on peut faire mieux. Disons que, comme l’on traite du réchauffement climatique, nous pourrions colorer en rouge le mot température. Pour cela, nous allons utiliser une balise html qui va entourer le mot. A l’intérieur de la balise d’ouverture indiquons la personnalisation souhaitée: style=‘color:red;’. C’est déjà mieux. Mais on peut aller plus loin en intégrant une image du drapeau britannique pour bien faire comprendre de qu’elle aire géographique que nous traitons. Cela tombe parce que j’ai justement en fichier .png avec le dit drapeau dans mon dossier de travail (source: Wikipedia). Comme dirait Sheldon Cooper : ’ fun with flag’. Pour l’intégrer, nous allons utiliser la balise html img. Nous indiquerons à l’intérieur l’adresse du fichier (ici juste src=“Flag_of_the_United_Kingdom.png”) et la taille que l’on veut voir occuper par l’image (width=‘20’). Il aura une largeur de 20 picels et une hauteur à même de respecter les proportions du dessin initial. Voyons ce que tout cela donne. Profitons-en pour aligner de titre au bord du graphe et pour choisir ‘Time New Roman’ comme police par défaut.</p>
<pre class="r"><code>library(ggtext)
G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;)+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown())</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<p>C’est pas mal! Vous ne trouvez pas? Un peu petit peut-être? Oui. Passons la taille de la police à 32 et essayons d’amener des contrastes plus doux en adoptant une couleur de fond de type sable (un beige clair tirant très légèrement sur le jaune sans être taupe). Mais comment trouvez le code correspondant à cette merveille? Le plus simple consiste à se rendre sur un site d’internet hébergeant une applet générant pour une couleur sélectionnée via une forme de roue chromatique le code correspondant. Essayons <a href="https://htmlcolorcodes.com/fr">htmlcolorcodes.com</a>. Après quelques tâtonnement, je trouve quelque chose que pourrait convenir: une couleur portant le doux nom de #F6F7F0. Je l’applique à plot.background.</p>
<pre class="r"><code>G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;)+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>C’est mieux, mais maintenant tout est #F6F7F0 (taupe claire voir sable). Je voudrais que la partie avec le nuage de point reste avec un fond blanc. Je vais donc l’indiquer dans panel.background. Ici, je peux indistinctement utiliser le mot white ou le code #FFFFFF. J’opte pour la seconde solution qui tellement plus poétique.</p>
<pre class="r"><code>G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;)+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>Les choses s’améliorent. Néanmoins, les axes ne sont pas très lisibles. On peut faire mieux. Commençons par redéfinir leurs limites. Dans <strong>coord_catesian()</strong> indiquons que l’on veut que l’axe des ordonnées commence à 7,35° et finisse à 11,1° et que l’axe des abscisses commence en 1770 et finissent en 2024. Revoyons également les graduations. Définissons les pas de numérotation (<em>breaks</em>) avec les compléments <strong>scale_y_continous()</strong> et <strong>scale_x_continous()</strong>. Prenons de 7.5° à 11° avec un pas de 0,5° pour l’ordonnée et de 1775 à 2025 avec un pas de 25 pour les abscisses. Profitons-en pour remettre le °C de l’axe des ordonnées dans le sens de la lecture.</p>
<pre class="r"><code>G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.title.y = element_text(angle=0,vjust=0.5))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>On peut rendre l’ensemble plus lisibles en augmentant la taille des caractères utilisés des axes. Disons 24 pour les titres et 18 pour la numérotation.</p>
<pre class="r"><code>G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.title.x= element_text(size=24),
         axis.title.y = element_text(angle=0,vjust=0.5,size=24),
         axis.text.x = element_text(size=18),
         axis.text.y = element_text(size=18))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>Voilà pour les axes! On peut maintenant s’attaquer au sous-titre qui apparaît trop petit et pas très parlant. Passons-le en taille 24 et modifions son texte. Disons que “Type de représentation: nuage de points” pourrait convenir.</p>
<pre class="r"><code>G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;,
        subtitle=&quot;Type de représentation : nuage de points&quot;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         plot.subtitle = element_text(face=&#39;italic&#39;,color=&#39;#697154&#39;,size=24),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.title.x= element_text(size=24),
         axis.title.y = element_text(angle=0,vjust=0.5,size=24),
         axis.text.x = element_text(size=18),
         axis.text.y = element_text(size=18))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>On avance, mais la légende est ridicule. Commençons par passer ses éléments (titre et texte) à la taille 24. Puis, ajoutons-lui un cadre à fond gris pour qu’elle ressorte plus nettement. Prenons un gris légèrement vert disons le #E1EAE7.</p>
<pre class="r"><code>G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;,
        subtitle=&quot;Type de représentation : nuage de points&quot;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         plot.subtitle = element_text(face=&#39;italic&#39;,color=&#39;#697154&#39;,size=24),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.title.x= element_text(size=24),
         axis.title.y = element_text(angle=0,vjust=0.5,size=24),
         axis.text.x = element_text(size=18),
         axis.text.y = element_text(size=18),
         legend.title = element_text(size=24),
         legend.text = element_text(size=24),
         legend.background = element_rect(fill=&#39;#E1EAE7&#39;,size=0.5))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Voilà qui est plus lisible. Reste le caption qui apparaît encore trop petit. Passons-le en taille 24 et décalons-le légèrement vers le bas. Profitons-en pour mettre “centre Hadley” en gras et la date en italique.</p>
<pre class="r"><code>G1+labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;,
        subtitle=&quot;Type de représentation : nuage de points&quot;,
        caption=&#39;Données: **centre Hadley** [Parker, Legg et Folland *(1992)*]&#39;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         plot.subtitle = element_text(face=&#39;italic&#39;,color=&#39;#697154&#39;,size=24),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.title.x= element_text(size=24),
         axis.title.y = element_text(angle=0,vjust=0.5,size=24),
         axis.text.x = element_text(size=18),
         axis.text.y = element_text(size=18),
         legend.title = element_text(size=24),
         legend.text = element_text(size=24),
         legend.background = element_rect(fill=&#39;#E1EAE7&#39;,size=0.5),
         plot.caption = element_markdown(margin=margin(t=15),size=24))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
<p>L’ensemble est maintenant cohérent. On pourrait s’arrêter là. On peut cependant encore améliorer les choses, par exemple, en marquant deux points remarquables celui correspondant à l’année la plus froide et celui correspondant à l’année la plus chaude. Commençons par la première.</p>
<pre class="r"><code>c(&#39;température:&#39;,min(dat$deg_C),&#39;année&#39;,dat$annee[dat$deg_C==min(dat$deg_C)])</code></pre>
<pre><code>## [1] &quot;température:&quot; &quot;7.43&quot;         &quot;année&quot;        &quot;1879&quot;</code></pre>
<p>Il s’agit de l’année 1879 pour laquelle la température moyenne a été de 7,43°. Nous allons utiliser le <strong>geom_point()</strong> pour le marquer avec pour esthétique (<em>aes()</em>) les coordonnées du point (x=1879 et y=7.43). Choisissons une couleur pour marquer le fait que ce soit un point froid. Disons un bleu très pale. Essayons le #BCE8F2. Complétons l’ensemble en ajoutant l’image d’un flocon de neige à coté du point (au cas où la couleur ne suffit pas…). J’en ai justement une stockée dans mon dossier de travail… Pour cela, nous utilisons le <strong>geom_richtext()</strong> qui est intégré dans ggtext. Retenons les mêmes coordonnées que notre point bleu. Indiquons en label un tag html avec l’adresse de l’image et la taille retenue. Pour éviter la superposition, retenons un paramètre de transparence alpha égale à 0 (totalement transparent), aucune couleur pour le label et très important un décalage de 10 sur l’axe des x (via nudge_x) et de 0,05 sur l’axe des y (nudge_y).</p>
<pre class="r"><code>G1+geom_point(aes(1879,7.43),color=&#39;#BCE8F2&#39;)+
   geom_richtext(aes(x=1879,y=7.43,label=&quot;&lt;img src=&#39;snow.png&#39;, width=&#39;20&#39; /&gt;&#39;&quot;),alpha=0,label.color = NA,nudge_x=10,nudge_y=0.05)+
   labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;,
        subtitle=&quot;Type de représentation : nuage de points&quot;,
        caption=&#39;Données: **centre Hadley** [Parker, Legg et Folland *(1992)*]&#39;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         plot.subtitle = element_text(face=&#39;italic&#39;,color=&#39;#697154&#39;,size=24),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.title.x= element_text(size=24),
         axis.title.y = element_text(angle=0,vjust=0.5,size=24),
         axis.text.x = element_text(size=18),
         axis.text.y = element_text(size=18),
         legend.title = element_text(size=24),
         legend.text = element_text(size=24),
         legend.background = element_rect(fill=&#39;#E1EAE7&#39;,size=0.5),
         plot.caption = element_markdown(margin=margin(t=15),size=24))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-19-1.png" width="672" /></p>
<p>L’ensemble est presque parfait. Reste que le flocon mange un peu l’axe des abscisses. Pour y remédier, étendons le taille de la figure à 8 pouces sur 8 pouces. Nous reviendrons sur ce type de manipulations dans un prochain poste (schématiquement ici j’indique dans les options de mon code chunk fig.height=8, fig.width=8). Ceci fait, attaquons-nous à l’année la plus chaude.</p>
<pre class="r"><code>c(&#39;température:&#39;,max(dat$deg_C),&#39;année:&#39;,dat$annee[dat$deg_C==max(dat$deg_C)])</code></pre>
<pre><code>## [1] &quot;température:&quot; &quot;10.95&quot;        &quot;année:&quot;       &quot;2014&quot;</code></pre>
<p>Il s’agit de 2014 avec une moyenne de 10,95°. Marquons-la d’un point orange (#F6A148) accompagné d’un petite image de soleil que l’on décalera cette fois vers la gauche de 10 (nudge_x=-10).</p>
<pre class="r"><code>G1+geom_point(aes(1879,7.43),color=&#39;#BCE8F2&#39;)+
   geom_richtext(aes(x=1879,y=7.43,label=&quot;&lt;img src=&#39;snow.png&#39;, width=&#39;20&#39; /&gt;&#39;&quot;),alpha=0,label.color = NA,nudge_x=10,nudge_y=0.05)+
   geom_point(aes(2014,10.95),color=&#39;#F6A148&#39;)+
   geom_richtext(aes(x=2014,y=10.95,label=&quot;&lt;img src=&#39;sun.png&#39;, width=&#39;20&#39; /&gt;&#39;&quot;),alpha=0,label.color = NA,nudge_x=-10,nudge_y=0.05)+
   labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;,
        width=&#39;20&#39; /&gt;&quot;,
        subtitle=&quot;Type de représentation : nuage de points&quot;,
        caption=&#39;Données: **centre Hadley** [Parker, Legg et Folland *(1992)*]&#39;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(size=32),
         plot.subtitle = element_text(face=&#39;italic&#39;,color=&#39;#697154&#39;,size=24),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.title.x= element_text(size=24),
         axis.title.y = element_text(angle=0,vjust=0.5,size=24),
         axis.text.x = element_text(size=18),
         axis.text.y = element_text(size=18),
         legend.title = element_text(size=24),
         legend.text = element_text(size=24),
         legend.background = element_rect(fill=&#39;#E1EAE7&#39;,size=0.5),
         plot.caption = element_markdown(margin=margin(t=15),size=24))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-21-1.png" width="768" /></p>
<p>Le graphe est maintenant encore plus parlant. Si le point le plus froid apparaît isolé en bas de graphe, ce n’est pas le cas du point le plus chaud. Le premier peut être considéré comme une observation exceptionnelle (un outlier). Le second lui marque une tendance claire au réchauffement climatique.</p>
<p>Ajoutons un encadré dans la figure pour en faciliter la lecture. Pour cela, utilisons le <strong>geom_textbox()</strong> proposé par ggtext. Il permet de personnaliser le texte avec des éléments de markdown et de htlm. Indiquons “Température annuelle:” avec à la ligne " maximum 10,95° constatée en 2014" et “minimum 7,43° constatée en 1879”. Le retour à la ligne se fait avec la balise &lt; BR &gt;. Profitons des fonctionnalités à disposition pour rependre les couleur des points dans le texte (orange pour le max et bleu pale pour le min). Plaçons l’encadré en bas à droite. Définissons sa taille: 0.3 pouces de large et 0.1 pouce de haut. Choisissons un gris un peu foncé comme couleur de fond (#A39380) de manière à le rendre plus visible. Assurons-nous que la police soit la même que sur le reste du graphe (<em>serif</em>) et choisissons un encrage gras. Finalement, fixons l’interligne à 0,7 pour que l’ensemble tienne bien dans la boite.</p>
<pre class="r"><code>G1+geom_textbox(aes(1972,7.7,
                label=&quot;Température annuelle:&lt;BR&gt;
                &lt;i style=&#39;color:#F6A148;&#39;&gt;maximum 10,95° constatée en 2014 &lt;/i&gt;
                &lt;i style=&#39;color:#BCE8F2;&#39;&gt;minimun 7,43° constatée en 1879 &lt;/i&gt;&quot;),
                fill=&#39;#A39380&#39;,family=&quot;serif&quot;, fontface=&#39;bold&#39;,
                size=7,
                width=0.3,
                height=0.1,
                lineheight = 0.7)+
   geom_point(aes(1879,7.43),color=&#39;#BCE8F2&#39;)+ 
   geom_richtext(aes(x=1879,y=7.43,label=&quot;&lt;img src=&#39;snow.png&#39;, width=&#39;20&#39; /&gt;&#39;&quot;),
                 alpha=0,label.color = NA,nudge_x=10,nudge_y=0.05)+
   geom_point(aes(2014,10.95),color=&#39;#F6A148&#39;)+
   geom_richtext(aes(x=2014,y=10.95,label=&quot;&lt;img src=&#39;sun.png&#39;, width=&#39;20&#39; /&gt;&#39;&quot;),
                 alpha=0,label.color = NA,nudge_x=-10,nudge_y=0.05)+
   labs(title =&quot;**&lt;i style=&#39;color:red;&#39;&gt;Températures&lt;/i&gt; moyennes au centre de l&#39;Angleterre** *(1772-2021)* &lt;img src=&#39;Flag_of_the_United_Kingdom.png&#39;, width=&#39;20&#39; /&gt;&quot;,
        subtitle=&quot;Type de représentation : nuage de points&quot;,
        caption=&#39;Données: **centre Hadley** [Parker, Legg et Folland *(1992)*]&#39;)+
   coord_cartesian(ylim=c(7.35, 11.1),xlim=c(1770,2024),expand =FALSE ) + 
   scale_y_continuous(breaks=seq(7.5, 11, 0.5))+
   scale_x_continuous(breaks=seq(1775, 2025, 25))+
   theme(text=element_text(family=&quot;serif&quot;),
         plot.background = element_rect(fill=&#39;#F6F7F0&#39;),
         plot.title.position = &#39;plot&#39;,
         plot.title = element_markdown(face = &#39;plain&#39;,hjust=0,size=32),
         plot.subtitle = element_text(face=&#39;italic&#39;,color=&#39;#697154&#39;,size=24),
         panel.background = element_rect(fill=&#39;#FFFFFF&#39;),
         axis.text.x = element_text(size=18),
         axis.text.y = element_text(size=18),
         axis.title.y = element_text(angle=0,vjust=0.5,size=24),
         axis.title.x= element_text(size=24),
         legend.title = element_text(size=24),
         legend.text = element_text(size=24),
         legend.background = element_rect(fill=&#39;#E1EAE7&#39;,size=0.5),
         plot.caption = element_markdown(margin=margin(t=15),size=24))</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/2021-09-02-police-academie/index_files/figure-html/unnamed-chunk-22-1.png" width="768" /></p>
<p>Nous obtenons au final un graphe vraiment parlant et surtout bien différent du matériel de base notamment grâce aux compléments proposés par ggtext.</p>
</div>


        <div class="share-icons d-flex justify-content-center d-print-none">
            <a href="https://twitter.com/intent/tweet?url=%2fpost%2f2021-09-02-police-academie%2f&text=Police%20academie&tw_p=tweetbutton" class="p-2" title="Share on Twitter" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Tweet</small></div>
</a>

<a href="https://www.facebook.com/sharer.php?u=%2fpost%2f2021-09-02-police-academie%2f&t=Police%20academie" class="p-2" title="Share on Facebook" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-facebook fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Share</small></div>
</a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url=%2fpost%2f2021-09-02-police-academie%2f&title=Police%20academie&source=mattbutton.com" class="p-2" title="Share on LinkedIn" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fab fa-linkedin fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Share</small></div>
</a>

<a href="javascript:window.print()" title="Print this article" class="p-2" target="_blank" rel="nofollow">
    <div>
        <span class="fa-stack">
            <i class="fas fa-circle fa-stack-2x"></i>
            <i class="fa fa-print fa-stack-1x fa-inverse"></i>
        </span>
    </div>
    <div class="fa-inverse text-center"><small>Print</small></div>
</a>
        </div>
    </div>

    
</div>
<div class="sidebar d-print-none d-none d-xl-block">
    
        <h2>My Econ Tricks</h2>
        <div>
            Blog académique tenu par Ludovic Vigneron, docteur en Finance et, depuis un certain nombre d&#39;années, Maître de Conférences à l&#39;Université Polytechnique Hauts de France.
        </div>
        <a href='/about/' class="btn btn-outline-secondary mt-3" role="button">Read More...</a>
        <h2 class="mt-4">Top Posts</h2>
    
    
    <h2 class="mt-4">Posts recents</h2>
    <nav class="nav flex-column">
        
        <a href="/post/2022-05-26-ttrer/" class="nav-link">ttrer</a>
        
        <a href="/post/2022-05-23-le-diagramme-en-chute-d-eau-gt12/" class="nav-link">Le diagramme en chute d&#39;eau GT12</a>
        
        <a href="/post/2022-05-10-le-diagramme-de-sankey-gt11/" class="nav-link">Le diagramme de Sankey GT11</a>
        
        <a href="/post/2022-05-05-bulles-de-comparaison-et-bulle-intriqu-e-gt10/" class="nav-link">Bulles de comparaison et bulle intriquée GT10</a>
        
        <a href="/post/2022-04-17-bullet-chart-et-gauge-chart-gt-9/" class="nav-link">Bullet chart et gauge chart GT9</a>
        
        <a href="/post/2022-04-10-test/" class="nav-link">Les heatmap et les calendar heatmap GT8</a>
        
        <a href="/post/2022-03-25-mes-premieres-videos-de-codage-de-graphes/" class="nav-link">Mes premieres videos de codage de graphes</a>
        
        <a href="/post/2022-04-29-les-diagramme-en-gaufre-et-les-isotypes-gt7/" class="nav-link">Les diagrammes en gaufre et les isotypes GT7</a>
        
    </nav>
    
    <h2 class="mt-4 text-capitalize">categories</h2>
    <nav class="nav flex-column">
        
        <a href='/categories/datavisualisation/' class="nav-link">
        datavisualisation
        <span class="badge badge-pill badge-secondary">19</span>
        </a>
        
        <a href='/categories/r/' class="nav-link">
        r
        <span class="badge badge-pill badge-secondary">16</span>
        </a>
        
        <a href='/categories/ggplot2/' class="nav-link">
        ggplot2
        <span class="badge badge-pill badge-secondary">6</span>
        </a>
        
        <a href='/categories/dataviz/' class="nav-link">
        dataviz
        <span class="badge badge-pill badge-secondary">2</span>
        </a>
        
        <a href='/categories/analysis/' class="nav-link">
        analysis
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/categories/mathematique/' class="nav-link">
        mathematique
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/categories/recherche/' class="nav-link">
        recherche
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/categories/software-development/' class="nav-link">
        software-development
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
    </nav>
    
    <h2 class="mt-4 text-capitalize">tags</h2>
    <nav class="nav flex-column">
        
        <a href='/tags/dataviz/' class="nav-link">
        dataviz
        <span class="badge badge-pill badge-secondary">19</span>
        </a>
        
        <a href='/tags/ggplot2/' class="nav-link">
        ggplot2
        <span class="badge badge-pill badge-secondary">17</span>
        </a>
        
        <a href='/tags/r/' class="nav-link">
        r
        <span class="badge badge-pill badge-secondary">11</span>
        </a>
        
        <a href='/tags/climat/' class="nav-link">
        climat
        <span class="badge badge-pill badge-secondary">3</span>
        </a>
        
        <a href='/tags/analysis/' class="nav-link">
        analysis
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/tags/crowdfunding/' class="nav-link">
        crowdfunding
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/tags/exercice/' class="nav-link">
        exercice
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/tags/mathematic/' class="nav-link">
        mathematic
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/tags/plotly/' class="nav-link">
        plotly
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
        <a href='/tags/publication/' class="nav-link">
        publication
        <span class="badge badge-pill badge-secondary">1</span>
        </a>
        
    </nav>
    
</div>

        </div>

        <footer class="mt-auto footer d-print-none">
            <div class="container-fluid">
                <div class="row justify-content-center">
                    <div class="col-md-4 col-xl-3">
                        <h5>© Ludovic Vigneroin 2021–2022. All rights reserved.</h5>
Content on this site is licensed under a Creative Commons Attribution 4.0 International license.
                    </div>
                    <div class="col-md-4 col-xl-3">
                        <h5>Disclaimer</h5>
Opinions expressed here are my own and may not reflect those of the company I work for, or the people I work with.
                    </div>
                    <div class="col-md-4 col-xl-3">
                        <h5>About This Site</h5>
This blog was created using the <a href="https://gohugo.io/">Hugo</a> static site generator, using
<a href="https://getbootstrap.com/">Bootstrap</a>, using the Silhouette Hugo theme, created by
<a href='https://www.mattbutton.com'>Matt Button</a>


    <script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
    
    <script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
    </script>
    
                    </div>
                </div>

                <hr />

                <div class="d-flex justify-content-center icons">
                    <a class="py-2 px-2" href="https://twitter.com/VigneronLudovic"><i class="fab fa-twitter"></i></a>
<a class="py-2 px-2" href="https://www.linkedin.com/in/ludovic-vigneron-1ba27749/"><i class="fab fa-linkedin"></i></a>
<a class="py-2 px-2" href='/index.xml'><i class="fas fa-rss"></i></a>

                </div>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

        
    </body>
</html>
