---
title: Quantitative Methods WRDS (1)
author: Ludovic Vigneron
date: '2022-09-01'
slug: []
categories:
  - R
  - Finance
tags:
  - R
  - Finance
---

**La rentrée universitaire est là. Et avec elle vient son lot de nouveaux cours d'autant que j'intègre une nouvelle université. Bref, les projets de l'été (ou au moins commencés cette été) et les data visualisations vont ralentir au moins un moment. Néanmoins, cela me donne l'occasion de partager d'autres types de contenus dans lesquels j'utilise R. C'est la cas du cours de Quantitative Methods dans lequel je présente aux étudiants les bases de données qu'ils peuvent utiliser pour leur future mémoire ainsi que les outils/techniques disponibles pour les exploiter. Ces étudiants se spécialisent en Finance. Le cours s'articule donc autour des bases souscrites via WRDS et notamment les très classiques CRPS et Compustat. A chaque fois, j'illustre ce que l'on peut faire de ces données à partir d'exemples classiques tirés du domaine ou en répliquant (au moins partiellement) des études réalisées sur ces données. C'est l'occasion non seulement de travailler les requêtes adressées aux bases, mais aussi la mise en forme des données et les techniques statistiques.**

Vous trouverez les slides de la première séance en utilisant le lien suivant:

[pdf_des_slides](Quantitative Methods test.pdf)

J'y aborde quelques généralités sur les bases données et R, puis à titre d'illustration j'estime le Bêta issu du MEDAF (CAPM) pour l'action Google (Alphabet).


