---
title: Do analysts matter for green investment? Evidence from the EU taxonomy
author: Ludovic Vigneron
date: '2025-04-02'
slug: []
categories:
  - Finance
  - recherche
tags:
  - Finance
  - Publication
  - Recherche
---

**Pour une fois ce fut rapide. Suite à une soumission déposé début décembre, et un parcours éditorial très efficace, le papier que j'ai co-écrit avec mes collègues Jean-Yves Filbien (Lumen - IAE de Lille) et Grégoire Davrinche (TBS Business-School) a été publié dans la revue de papiers courts Economonics Letters. Nous y montrons que l'intérêt des analystes financiers pour les questions écologiques, et plus particulièrement le climat, est positivement associé avec la propension qu'ont les entreprises à réaliser des investissements verts. Nous apportons des éléments plaidant pour l'existence d'une relation allant dans ce sens. L'étude porte sur des entreprises françaises cotées (CAC-All tradable). La mesure l'investissement vert est réalisée à partir de la taxonomie européenne au travers du ratio capex aligné sur capex éligible, autrement-dit de ce qui est fait réellement comparé à ce qu'il est a priori possible de faire selon la taxonomie. Les données utilisées sont celles des deux premières années de publication des informations pro format. Elles ont été recueillies à la main (je remercie pour cela mes co-auteurs qui m'ont épargné cette tache alors que je finalisais mes supports de soutenance de HDR - j'espère leur rendre l'appareil rapidement). Ces données sont précieuses. Non seulement, elles ont demandé pas mal de travail pour être obtenu mais aussi parce que bien souvent les papiers "utilisant" l'information sur les rapports associés à la taxonomie se basent sur de simples estimations (disons discutables dans la mesure notamment où les bases concernées donnent des valeurs même pour des entreprises non soumis à la taxonomie - il faudrait avoir plus d'information sur la manière dont ces estimations sont faites et sur leur validité, leur comparaisons avec les vraies valeurs lorsqu'elles existent...). Concernant l'intérêt des analystes pour les questions environnementales/ climats, nous avons utilisé la mesure proposées par Sautner et al (2023) qui construise un indice le reflétant à partir du traitement des *conference call* (ces séquences où les analystes interrogent directement les dirigeants d'entreprise sur leur résultat).**

Je vous met ici le résumé du papier :

**To mitigate climate warming, one critical strategy is to redirect corporate investments toward low-carbon projects. This study explores the role that financial analysts’ focus on environmental issues can play in this process. The research leverages the implementation of the EU Taxonomy Regulation for publicly listed companies in France during the period 2022–2023, which provides a comprehensive, precise, and standardized measure of corporate green investments. We use a firm-level measure of climate change exposure as a proxy for analysts’ attention on environmental issues. We find that analyst attention has a positive and significant effect on corporate green investments. Our results remain robust to potential self-selection bias and reverse causality. In a further analysis, we also find that our main result is driven by analysts’ focus on opportunities. This study offers new insights into how analyst scrutiny impacts ESG practices and highlights the potential contributions of the EU Taxonomy Regulation.**

Je met également un lien pour pouvoir le lire en entier: [Economics Letters Avril 2025](https://doi.org/10.1016/j.econlet.2025.112277). Il est en accès libre sur le site de la revue.

Un des enseignements/implications du papiers est qu'il peut être intéressant dans le cadre de la lutte contre le réchauffement climatique d'actionner le levier de l'influence des analystes financiers pour encourager les entreprises à "verdir" leurs politiques.

J'espère que ce travail vous intéressera. Il sera surement suivi d'autres permettant d'approfondir de ce type de questions (investissement verts, barrières, motivations, incitations, greenwashing...). C'est une voie de recherche que je comptes bien approfondir à l'avenir. more to come i hope.
