---
title: 'Techniques Quantitatives de Gestion : exploitation des données (4)'
author: Ludovic Vigneron
date: '2022-09-25'
slug: []
categories:
  - Cours
  - R
tags:
  - Cours
  - Exercice
  - R
---



<p><strong>Dans ce nouveau post, nous allons continuer à travailler sur la régression. L’objectif est de considérer des tests alternatifs sur les coefficient et d’étendre les modèles de manière à intégrer plusieurs facteurs explicatifs. Cela nous permettra de comprendre les biais créés par l’omission de variables dans les analyses de régression.</strong></p>
<div id="tâche-n1-reprenez-les-données-sur-les-actions-estimez-le-modèle-de-marché-pour-chacun-deux-réalisez-un-interval-de-confiance-à-95-sur-le-beta-testez-sa-valeur-par-rapport-à-1." class="section level1">
<h1>Tâche n°1 Reprenez les données sur les actions, estimez le modèle de marché pour chacun d’eux, réalisez un interval de confiance à 95% sur le beta, testez sa valeur par rapport à 1.</h1>
<p>Comme à chaque fois, nous allons commencer par charger les packages qui vont être utilisés. On y retrouve les habituels <em>tidyverse</em>, <em>haven</em>, <em>gt</em>, mais aussi <em>car</em>, un nouveau package qui inclue des fonctions permettant la réalisation de tests statistiques complémentaires aux régressions.</p>
<pre class="r"><code>library(tidyverse)
library(haven)
library(gt)
library(car)</code></pre>
<p>On peut alors importer les données concernant les rendements des actions et de l’indice de marché que nous avons créé dans le post précédent. Si nécessaire vous pouvez le télécharger <a href="return_actions.csv">ici</a>.</p>
<pre class="r"><code>return_actions &lt;- read_delim(&quot;return_actions.csv&quot;,delim = &quot;;&quot;)</code></pre>
<pre><code>## Rows: 252 Columns: 9
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;;&quot;
## dbl  (8): MSFT.Adjusted, AAPL.Adjusted, META.Adjusted, GSPC.Adjusted, ret_MS...
## date (1): Date
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>Ceux-ci fait. On peut ré-estimer le modèle de marché pour chaque titre (régression du rendement de l’action sur l’indice de marché en utilisant la fonction <strong>lm()</strong>) et stocker l’information dans des objets dédiés (portant ici le noms des actions).</p>
<pre class="r"><code>Ms&lt;-lm(ret_MSFT~ret_GSPC,data=return_actions)
Ap&lt;-lm(ret_AAPL~ret_GSPC,data=return_actions)
Fb&lt;-lm(ret_META~ret_GSPC,data=return_actions)</code></pre>
<p>Pour obtenir l’interval de confiance au niveau désiré (95%), il suffit de mobiliser la fonction <strong>confint()</strong>. Elle prend comme premier argument le modèle de régession et comme second (level) le niveau de confiance retenu. Produisons-la pour Microsoft (Ms).</p>
<pre class="r"><code>confint(Ms,level=0.95) </code></pre>
<pre><code>##                    2.5 %      97.5 %
## (Intercept) -0.001112434 0.001401162
## ret_GSPC     1.083637524 1.390103522</code></pre>
<p>On peut lire que le Beta de Microsoft à 95% de chance de se trouver entre 1.083 et 1.390. Néanmoins, l’ensemble reste peut lisible du fait de l’inclusion de l’intervalle de confiance de la constante et du nombre de chiffres après la virgule affiché. Réduisons tout cela.</p>
<pre class="r"><code>confint(Ms,parm=2,level=0.95) %&gt;% round(digits = 4)</code></pre>
<pre><code>##           2.5 % 97.5 %
## ret_GSPC 1.0836 1.3901</code></pre>
<p>Créons un tableau incluant l’ensemble des intervalles de confiance des beta des titre.</p>
<pre class="r"><code>tb&lt;-rbind(confint(Ms,parm=2,level=0.95),
          confint(Ap,parm=2,level=0.95),
          confint(Fb,parm=2,level=0.95)) %&gt;% round(digits=4)
rownames(tb)&lt;-NULL
tb</code></pre>
<pre><code>##       2.5 % 97.5 %
## [1,] 1.0836 1.3901
## [2,] 0.8396 1.2078
## [3,] 0.8588 1.3279</code></pre>
<p>Incluons-les dans le tableau des beta tel que nous l’avions réalisé dans le post précédent.</p>
<pre class="r"><code>reg1&lt;-summary(Ms)
reg2&lt;-summary(Ap)
reg3&lt;-summary(Fb)
tab&lt;-data.frame(c(&#39;Microsoft&#39;,&#39;Apple&#39;,&#39;Facebook&#39;),
                rbind(round(reg1$coefficients[2,c(1,3,4)],digits=4),
                      round(reg2$coefficients[2,c(1,3,4)],digits=4),
                      round(reg3$coefficients[2,c(1,3,4)],digits=4)),
                tb) 
colnames(tab)&lt;-c(&#39; &#39;,&#39;Beta&#39;,&#39;t stat&#39;, &#39;p value&#39;,&#39;2,5%&#39;,&#39;97,5%&#39;)
tab$`p value`&lt;-format(tab$`p value`,nsmall = 4)
tab</code></pre>
<pre><code>##               Beta  t stat p value   2,5%  97,5%
## 1 Microsoft 1.2369 15.8978  0.0000 1.0836 1.3901
## 2     Apple 1.0237 10.9531  0.0000 0.8396 1.2078
## 3  Facebook 1.0934  9.1810  0.0000 0.8588 1.3279</code></pre>
<p>Ajoutons un titre, un sous-titre ainsi qu’un chapeau sur les colonnes correspondant à l’intervalle de confiance.</p>
<pre class="r"><code>tab_&lt;-gt(tab) %&gt;% 
  tab_header(title=&#39;Beta issu du modèle de marché&#39;,
             subtitle = &quot;Estimé sur 2016 en référence à l&#39;indice S&amp;P500&quot;) %&gt;% 
  tab_spanner(&#39;Interval de confiance à 95%&#39;,columns = c(&#39;2,5%&#39;,&#39;97,5%&#39;))
tab_</code></pre>
<div id="hmolsiiqkc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#hmolsiiqkc .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#hmolsiiqkc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hmolsiiqkc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#hmolsiiqkc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#hmolsiiqkc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hmolsiiqkc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#hmolsiiqkc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#hmolsiiqkc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#hmolsiiqkc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#hmolsiiqkc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#hmolsiiqkc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#hmolsiiqkc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#hmolsiiqkc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#hmolsiiqkc .gt_from_md > :first-child {
  margin-top: 0;
}

#hmolsiiqkc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#hmolsiiqkc .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#hmolsiiqkc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#hmolsiiqkc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#hmolsiiqkc .gt_row_group_first td {
  border-top-width: 2px;
}

#hmolsiiqkc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hmolsiiqkc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#hmolsiiqkc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#hmolsiiqkc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hmolsiiqkc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#hmolsiiqkc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#hmolsiiqkc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#hmolsiiqkc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#hmolsiiqkc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hmolsiiqkc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hmolsiiqkc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#hmolsiiqkc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#hmolsiiqkc .gt_left {
  text-align: left;
}

#hmolsiiqkc .gt_center {
  text-align: center;
}

#hmolsiiqkc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#hmolsiiqkc .gt_font_normal {
  font-weight: normal;
}

#hmolsiiqkc .gt_font_bold {
  font-weight: bold;
}

#hmolsiiqkc .gt_font_italic {
  font-style: italic;
}

#hmolsiiqkc .gt_super {
  font-size: 65%;
}

#hmolsiiqkc .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#hmolsiiqkc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#hmolsiiqkc .gt_indent_1 {
  text-indent: 5px;
}

#hmolsiiqkc .gt_indent_2 {
  text-indent: 10px;
}

#hmolsiiqkc .gt_indent_3 {
  text-indent: 15px;
}

#hmolsiiqkc .gt_indent_4 {
  text-indent: 20px;
}

#hmolsiiqkc .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="6" class="gt_heading gt_title gt_font_normal" style>Beta issu du modèle de marché</td>
    </tr>
    <tr>
      <td colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Estimé sur 2016 en référence à l'indice S&amp;P500</td>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col"> </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col">Beta</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col">t stat</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col">p value</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup">
        <span class="gt_column_spanner">Interval de confiance à 95%</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">2,5%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">97,5%</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Microsoft</td>
<td class="gt_row gt_right">1.2369</td>
<td class="gt_row gt_right">15.8978</td>
<td class="gt_row gt_right">0.0000</td>
<td class="gt_row gt_right">1.0836</td>
<td class="gt_row gt_right">1.3901</td></tr>
    <tr><td class="gt_row gt_left">Apple</td>
<td class="gt_row gt_right">1.0237</td>
<td class="gt_row gt_right">10.9531</td>
<td class="gt_row gt_right">0.0000</td>
<td class="gt_row gt_right">0.8396</td>
<td class="gt_row gt_right">1.2078</td></tr>
    <tr><td class="gt_row gt_left">Facebook</td>
<td class="gt_row gt_right">1.0934</td>
<td class="gt_row gt_right">9.1810</td>
<td class="gt_row gt_right">0.0000</td>
<td class="gt_row gt_right">0.8588</td>
<td class="gt_row gt_right">1.3279</td></tr>
  </tbody>
  
  
</table>
</div>
<p>Transférons le résultat dans un document Word.</p>
<pre class="r"><code>gtsave(tab_,&#39;Betas_conf_v1.docx&#39;)</code></pre>
<p>Il nous reste à réaliser les test des beta contre la valeur 1. Les tests dans les modèles de régression sont réalisés contre 0. Pour cela, on peut utiliser la fonction <strong>linearHypothesis()</strong> du package <em>car</em>. Elle permet de mettre en oeuvre un test de restriction spécification de Fisher. Ses arguments sont le modèle de régression et la restriction (ici ret_GSPC=1).</p>
<pre class="r"><code>linearHypothesis(Ms, &quot;ret_GSPC = 1&quot;)</code></pre>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## ret_GSPC = 1
## 
## Model 1: restricted model
## Model 2: ret_MSFT ~ ret_GSPC
## 
##   Res.Df      RSS Df  Sum of Sq      F  Pr(&gt;F)   
## 1    250 0.026314                                
## 2    249 0.025370  1 0.00094442 9.2693 0.00258 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Pratiqué pour Microsoft, on rejette l’hypothèse H1 d’égalité du coefficient à 1 (que le modèle restreint est meilleur que le modèle de base). Appliquons la même procédure qui a un beta plus proche de 1.</p>
<pre class="r"><code>linearHypothesis(Ap, &quot;ret_GSPC = 1&quot;)</code></pre>
<pre><code>## Linear hypothesis test
## 
## Hypothesis:
## ret_GSPC = 1
## 
## Model 1: restricted model
## Model 2: ret_AAPL ~ ret_GSPC
## 
##   Res.Df      RSS Df  Sum of Sq      F Pr(&gt;F)
## 1    250 0.036621                            
## 2    249 0.036612  1 9.4582e-06 0.0643    0.8</code></pre>
<p>Cette fois ci, on ne peut rejeté H0. Le beta de Apple n’est pas statistiquement différent de 1.</p>
<p>La procédure rempli ses objectifs. Néanmoins, on pourrait préférer utiliser un test de Student comme pour l’hypothèse classique de beta égale 0 que l’on retrouve dans les résumés des modèles de régression. Pour cela, le plus simple (pour moi) est de créer soit même sa fonction de test. Rappelons la forme de statistique de Sudent:</p>
<p><span class="math display">\[Beta=\frac{\hat{\beta}-1}{\sigma/\sqrt{n}}\]</span>
où</p>
<p><span class="math display">\[\text{Standard error}=\sigma/\sqrt{n}\]</span></p>
<p>La fonction <strong>pt()</strong> permet de calculer la fonction de densité cumulative (la fonction de répartition) de la loi de Student. Mobilisons-la pour calculer la p value du test.</p>
<pre class="r"><code>ttest &lt;- function(reg, coefnum, val){
  co &lt;- coef(summary(reg))
  tstat &lt;- (co[coefnum,1]-val)/co[coefnum,2]
  pval&lt;- 2 * pt(abs(tstat), reg$df.residual, lower.tail = FALSE)
  ret&lt;-round(c(tstat,pval),digits=4)
  names(ret)&lt;-c(&#39;tstat&#39;,&#39;pval&#39;)
  return(ret)}</code></pre>
<p>Appliquons notre fonction à la régression sur Microsoft (Ms) d’abord en testant beta égal à 0 pour comparer le résultat avec celui obtenu avec la fonction <strong>summary()</strong>, puis en testant beta égal à 1.</p>
<pre class="r"><code>ttest(Ms,2,0)</code></pre>
<pre><code>##   tstat    pval 
## 15.8978  0.0000</code></pre>
<pre class="r"><code>ttest(Ms,2,1)</code></pre>
<pre><code>##  tstat   pval 
## 3.0445 0.0026</code></pre>
<p>Notre fonction maison produit bien le résultat attendu. Appliquons-la à toute nos actions. Agrégeons l’ensemble pour l’ajouter à notre tableau des beta.</p>
<pre class="r"><code>tc&lt;-rbind(ttest(Ms,2,1),ttest(Ap,2,1),ttest(Fb,2,1))
tc</code></pre>
<pre><code>##       tstat   pval
## [1,] 3.0445 0.0026
## [2,] 0.2536 0.8000
## [3,] 0.7842 0.4337</code></pre>
<p>Créons la data frame correspondant.</p>
<pre class="r"><code>tab&lt;-data.frame(tab,tc) 
colnames(tab)&lt;-c(&#39; &#39;,&#39;Beta&#39;,&#39;t stat&#39;, &#39;p value&#39;,&#39;2,5%&#39;,&#39;97,5%&#39;,
                 &#39;t_stat&#39;, &#39;p_value&#39;)
tab</code></pre>
<pre><code>##               Beta  t stat p value   2,5%  97,5% t_stat p_value
## 1 Microsoft 1.2369 15.8978  0.0000 1.0836 1.3901 3.0445  0.0026
## 2     Apple 1.0237 10.9531  0.0000 0.8396 1.2078 0.2536  0.8000
## 3  Facebook 1.0934  9.1810  0.0000 0.8588 1.3279 0.7842  0.4337</code></pre>
<p>Mettons l’ensemble en page.</p>
<pre class="r"><code>tab_&lt;-gt(tab) %&gt;% 
  tab_header(title=&#39;Beta issu du modèle de marché&#39;,
             subtitle = &quot;Estimé sur 2016 en référence à l&#39;indice S&amp;P500&quot;) %&gt;% 
  tab_spanner(&#39;Beta=0&#39;,columns = c(&#39;t stat&#39;,&#39;p value&#39;)) %&gt;% 
  tab_spanner(&#39;Interval de confiance à 95%&#39;,columns = c(&#39;2,5%&#39;,&#39;97,5%&#39;)) %&gt;% 
  tab_spanner(&#39;Beta=1&#39;,columns = c(&#39;t_stat&#39;,&#39;p_value&#39;)) 
tab_</code></pre>
<div id="umsugmagkg" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#umsugmagkg .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 16px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#umsugmagkg .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#umsugmagkg .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#umsugmagkg .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#umsugmagkg .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#umsugmagkg .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#umsugmagkg .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#umsugmagkg .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: normal;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#umsugmagkg .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#umsugmagkg .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#umsugmagkg .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#umsugmagkg .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#umsugmagkg .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#umsugmagkg .gt_from_md > :first-child {
  margin-top: 0;
}

#umsugmagkg .gt_from_md > :last-child {
  margin-bottom: 0;
}

#umsugmagkg .gt_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#umsugmagkg .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#umsugmagkg .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#umsugmagkg .gt_row_group_first td {
  border-top-width: 2px;
}

#umsugmagkg .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#umsugmagkg .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#umsugmagkg .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#umsugmagkg .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#umsugmagkg .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#umsugmagkg .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#umsugmagkg .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#umsugmagkg .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#umsugmagkg .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#umsugmagkg .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#umsugmagkg .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#umsugmagkg .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#umsugmagkg .gt_left {
  text-align: left;
}

#umsugmagkg .gt_center {
  text-align: center;
}

#umsugmagkg .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#umsugmagkg .gt_font_normal {
  font-weight: normal;
}

#umsugmagkg .gt_font_bold {
  font-weight: bold;
}

#umsugmagkg .gt_font_italic {
  font-style: italic;
}

#umsugmagkg .gt_super {
  font-size: 65%;
}

#umsugmagkg .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#umsugmagkg .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#umsugmagkg .gt_indent_1 {
  text-indent: 5px;
}

#umsugmagkg .gt_indent_2 {
  text-indent: 10px;
}

#umsugmagkg .gt_indent_3 {
  text-indent: 15px;
}

#umsugmagkg .gt_indent_4 {
  text-indent: 20px;
}

#umsugmagkg .gt_indent_5 {
  text-indent: 25px;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <td colspan="8" class="gt_heading gt_title gt_font_normal" style>Beta issu du modèle de marché</td>
    </tr>
    <tr>
      <td colspan="8" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Estimé sur 2016 en référence à l'indice S&amp;P500</td>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1" scope="col"> </th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="2" colspan="1" scope="col">Beta</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup">
        <span class="gt_column_spanner">Beta=0</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup">
        <span class="gt_column_spanner">Interval de confiance à 95%</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2" scope="colgroup">
        <span class="gt_column_spanner">Beta=1</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">t stat</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">p value</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">2,5%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">97,5%</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">t_stat</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col">p_value</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Microsoft</td>
<td class="gt_row gt_right">1.2369</td>
<td class="gt_row gt_right">15.8978</td>
<td class="gt_row gt_right">0.0000</td>
<td class="gt_row gt_right">1.0836</td>
<td class="gt_row gt_right">1.3901</td>
<td class="gt_row gt_right">3.0445</td>
<td class="gt_row gt_right">0.0026</td></tr>
    <tr><td class="gt_row gt_left">Apple</td>
<td class="gt_row gt_right">1.0237</td>
<td class="gt_row gt_right">10.9531</td>
<td class="gt_row gt_right">0.0000</td>
<td class="gt_row gt_right">0.8396</td>
<td class="gt_row gt_right">1.2078</td>
<td class="gt_row gt_right">0.2536</td>
<td class="gt_row gt_right">0.8000</td></tr>
    <tr><td class="gt_row gt_left">Facebook</td>
<td class="gt_row gt_right">1.0934</td>
<td class="gt_row gt_right">9.1810</td>
<td class="gt_row gt_right">0.0000</td>
<td class="gt_row gt_right">0.8588</td>
<td class="gt_row gt_right">1.3279</td>
<td class="gt_row gt_right">0.7842</td>
<td class="gt_row gt_right">0.4337</td></tr>
  </tbody>
  
  
</table>
</div>
<p>Transférons le tableau produit dans Word.</p>
<pre class="r"><code>gtsave(tab_,&#39;Betas_conf_0_1_v1.docx&#39;)</code></pre>
</div>
<div id="tâche-n2-revenez-sur-les-cas-des-écoles-californiennes-incluez-dans-la-régresion-les-variables-déléves-apprenant-langlais-el_pct-étudiez-les-liens-entre-les-variables" class="section level1">
<h1>Tâche n°2 Revenez sur les cas des écoles californiennes, incluez dans la régresion les variables d’éléves apprenant l’anglais (el_pct), étudiez les liens entre les variables</h1>
<p>Commençons par recharger les données associés aux écoles (le fichier caschool). Si vous ne les avez pas encore vous pouvez les trouver en lien <a href="caschool.dta">ici</a>.</p>
<pre class="r"><code>caschool &lt;- read_dta(&quot;caschool.dta&quot;)</code></pre>
<p>Une fois les données importées, créons deux modèles de régression le premier expliquant testscr uniquement avec str (reg1) et le secons l’expliquant à la fois par str et el_pct.</p>
<pre class="r"><code>reg1&lt;-lm(testscr~str,data=caschool)
reg2&lt;-lm(testscr~str+el_pct,data=caschool)</code></pre>
<p>Inspectons le résultat de la première régression via <strong>summary()</strong>.</p>
<pre class="r"><code>summary(reg1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = testscr ~ str, data = caschool)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -47.727 -14.251   0.483  12.822  48.540 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 698.9330     9.4675  73.825  &lt; 2e-16 ***
## str          -2.2798     0.4798  -4.751 2.78e-06 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 18.58 on 418 degrees of freedom
## Multiple R-squared:  0.05124,    Adjusted R-squared:  0.04897 
## F-statistic: 22.58 on 1 and 418 DF,  p-value: 2.783e-06</code></pre>
<p>Le coefficient associé à str est de -2.2798 et il est statistiquement différent de zéro. Voyons ce qu’il en est dans le second modèle.</p>
<pre class="r"><code>summary(reg2)</code></pre>
<pre><code>## 
## Call:
## lm(formula = testscr ~ str + el_pct, data = caschool)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -48.845 -10.240  -0.308   9.815  43.461 
## 
## Coefficients:
##              Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept) 686.03225    7.41131  92.566  &lt; 2e-16 ***
## str          -1.10130    0.38028  -2.896  0.00398 ** 
## el_pct       -0.64978    0.03934 -16.516  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 14.46 on 417 degrees of freedom
## Multiple R-squared:  0.4264, Adjusted R-squared:  0.4237 
## F-statistic:   155 on 2 and 417 DF,  p-value: &lt; 2.2e-16</code></pre>
<p>La valeur du coefficient de str a changé. Elle est passée à -1.1013 mais est toujours statistiquement significatif. Le coefficient de el_pct est de -0.6497 et est statistiquement significatif.</p>
<p>Pour bien comprendre comment l’inclusion d’el_pct permet d’ajuster l’effet de str sur testscr, régressons str par el_pct. Cela nous indique l’effet de el_pct sur str. Sortons les résidus de la régression autrement dit la part de str non expliquée par el_pct.</p>
<pre class="r"><code>rega&lt;-lm(str~el_pct,data=caschool)
res_a&lt;-rega$residuals
head(res_a)</code></pre>
<pre><code>##          1          2          3          4          5          6 
## -1.4444089  2.1013692 -1.2194820 -1.9771752 -0.9320077  1.8310406</code></pre>
<p>Régressons de la même manière testscr par el_pct et sortons le résidus, la part de testscr non expliqué par el_pct.</p>
<pre class="r"><code>regb&lt;-lm(testscr~el_pct,data=caschool)
res_b&lt;-regb$residuals
head(res_b)</code></pre>
<pre><code>##           1           2           3           4           5           6 
##  26.0605447  -0.4632982  -1.0047804 -17.0394308 -14.5888014 -50.8611787</code></pre>
<p>Régressons ce dernier résidu par le premier en omettant la constante. Cela se fait en ajoutant -1 aux variables explicatives.</p>
<pre class="r"><code>lm(res_b~res_a-1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = res_b ~ res_a - 1)
## 
## Coefficients:
##  res_a  
## -1.101</code></pre>
<p>On retrouve retrouve le même coefficient que dans notre modèle incluant les deux variables pour expliquer testscr. L’inclusion de la seconde variable permet bien de corriger l’effet de str sur testscr de la partie de cet effet qui passe par el_pct.</p>
</div>
